CREATE TABLE ACCOUNT(
    ACCOUNT_CODE CHAR(7) PRIMARY KEY,
    ACCOUNT_NAME VARCHAR(40) NOT NULL CHECK(ACCOUNT_NAME LIKE '%　%'),
    TYPE CHAR(1) NOT NULL,
    BALANCE INTEGER NOT NULL CHECK(BALANCE >= 0),
    UPDATE_AT DATE
);

CREATE TABLE ABOLISHMENT_ACCOUNT(
    ACCOUNT_CODE CHAR(7) PRIMARY KEY,
    ACCOUNT_NAME VARCHAR(40) NOT NULL CHECK(ACCOUNT_NAME LIKE '%　%'),
    TYPE CHAR(1) NOT NULL,
    BALANCE_AT_ABOLISHMENT INTEGER NOT NULL CHECK(BALANCE_AT_ABOLISHMENT >= 0),
    ABOLISHMENT_DAY DATE
);

CREATE TABLE TRAIDING(
    TRAIDING_CODE INTEGER PRIMARY KEY,
    TRAIDING_DETAIL_ID INTEGER REFERENCES TRAIDING_DETAIL(ID),
    DAY DATE NOT NULL,
    ACCOUNT_CODE CHAR(7) NOT NULL,
    DEPOSIT_AMOUNT INTEGER,
    WITHDRAWAL_AMOUNT INTEGER
);

CREATE TABLE TRAIDING_DETAIL(
    ID INTEGER PRIMARY KEY,
    DETAIL VARCHAR(20) NOT NULL
);
