INSERT INTO TRAIDING_DETAIL(ID, DETAIL)
    VALUES(1, '預入');
INSERT INTO TRAIDING_DETAIL(ID, DETAIL)
    VALUES(2, '引出');
INSERT INTO TRAIDING_DETAIL(ID, DETAIL)
    VALUES(3, '振込');
INSERT INTO TRAIDING_DETAIL(ID, DETAIL)
    VALUES(4, '通帳記入');
INSERT INTO TRAIDING_DETAIL(ID, DETAIL)
    VALUES(5, '残高照会');
INSERT INTO TRAIDING_DETAIL(ID, DETAIL)
    VALUES(6, '手数料引落');
INSERT INTO TRAIDING_DETAIL(ID, DETAIL)
    VALUES(9, 'その他');