-- 25. 商品区分「衣類」の商品について、商品コードの降順に商品コードと商品名の一覧を取得する。
SELECT CODE, NAME FROM PRODUCTS WHERE CATEGORIES = 1 ORDER BY CODE DESC;

-- 26. 注文テーブルから、主キーの昇順に2022年3月以降の注文一覧を取得する。取得する項目は、注文日、注文番号、注文枝番、商品コード、数量とする。
SELECT ORDERS_DATE, ORDERS_NUMBER, ORDERS_BRANCH_NUM, PRODUCTS_CODE 
FROM ORDERS
WHERE '2022-03-01' <= ORDERS_DATE
ORDER BY ORDERS_NUMBER ASC;

-- 27. 注文テーブルから、これまでに注文のあった商品コードを抽出する。重複は除外し、商品コードの昇順に抽出すること。
SELECT PRODUCTS_CODE FROM ORDERS GROUP BY PRODUCTS_CODE;
SELECT DISTINCT PRODUCTS_CODE FROM ORDERS;

-- 28. 注文テーブルから、注文のあった日付を新しい順に10行抽出する（同一日付が複数回登場してもよい。）
SELECT ORDERS_DATE 
FROM ORDERS
ORDER BY ORDERS_DATE ASC
OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;

-- 29. 商品テーブルから、単価の低い順に並べて6〜20行目に当たる商品データを抽出する。同一の単価の場合は、商品区分、商品コードの昇順に並ぶように抽出すること。
SELECT * FROM PRODUCTS
ORDER BY PRICE ASC, CATEGORIES ASC, CODE ASC
OFFSET 6 ROWS FETCH NEXT 15 ROWS ONLY;

-- 30. 廃番商品テーブルから、2020年12月に廃番されたものと、売上個数が100を超えるものを併せて抽出する。一覧は、売上個数の多い順に並べること。
SELECT * FROM ABOLISHMENT_PRODUCTS
WHERE ('2020-12-01' <= ABOLISHMENT_DATE AND '2020-12-31' >= ABOLISHMENT_DATE) OR NUMBER_OF_SALES > 100
ORDER BY NUMBER_OF_SALES DESC;

-- 31. 商品テーブルから、これまでに注文されたことのない商品コードを昇順に抽出する。
SELECT PRODUCTS.CODE FROM PRODUCTS
LEFT JOIN ORDERS
ON PRODUCTS.CODE = ORDERS.PRODUCTS_CODE
WHERE ORDERS.PRODUCTS_CODE IS NULL
ORDER BY PRODUCTS.CODE ASC;

-- 32. 商品テーブルから、これまでに注文された実績のある商品コードを抽出する。
SELECT PRODUCTS.CODE FROM PRODUCTS
LEFT JOIN ORDERS
ON PRODUCTS.CODE = ORDERS.PRODUCTS_CODE
WHERE ORDERS.PRODUCTS_CODE IS NOT NULL
ORDER BY PRODUCTS.CODE DESC;

-- 33. 商品区分が「未分類」で、単価が千円以下と1万円を超える商品について、商品コード、商品名、単価を抽出する。単価の低い順に並べ、同額の場合は商品コードの昇順とする。
SELECT CODE, NAME, PRICE 
FROM PRODUCTS
WHERE CATEGORIES = '9' AND (PRICE <= 1000 OR PRICE > 10000)
ORDER BY PRICE DESC, CODE ASC;