-- 46. これまでに注文された数量の合計を求める。
SELECT COUNT(ORDERS_NUMBER) AS 注文合計 FROM ORDERS;

-- 47. 注文日順に、注文日ごとの数量の合計を求める。
SELECT ORDERS_DATE, COUNT(ORDERS_NUMBER) AS 注文日ごとの合計数量 FROM ORDERS
GROUP BY ORDERS_DATE;

-- 48. 商品区分順に、商品区分ごとの単価の最小額と最高額を求める。
SELECT *, MIN(PRICE) AS 最小額, MAX(PRICE) AS 最高額 FROM PRODUCTS
GROUP BY CATEGORIES
ORDER BY CATEGORIES ASC;

-- 49. 商品コードごとに、これまで注文された数量の合計を商品コード順に求める。
SELECT PRODUCTS_CODE, COUNT(ORDERS_NUMBER) AS 注文数量の合計 FROM ORDERS
GROUP BY PRODUCTS_CODE
ORDER BY PRODUCTS_CODE ASC;

-- 50.これまでに最もよく売れた商品を10位まで抽出する。商品コードと販売した数量を数量の多い順に並べ、
-- 　　数量が同じ商品については、商品コードの昇順にすること。
SELECT PRODUCTS_CODE, COUNT(ORDERS_NUMBER) AS SUM FROM ORDERS
GROUP BY ORDERS_NUMBER
ORDER BY SUM DESC, PRODUCTS_CODE ASC
OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;

-- 51. これまでに売れた数量が5個未満の商品コードとその数量を抽出する。
SELECT PRODUCTS_CODE, COUNT(PRODUCTS_CODE) AS SUM FROM ORDERS
GROUP BY PRODUCTS_CODE
HAVING SUM < 5;

-- 52. これまでにクーポン割引をした注文件数と、割引額の合計を求める。ただし、WHERE句による絞り込み条件は指定しないこと。
SELECT COUNT(COUPON_DISCOUNT_TICKET), SUM(COUPON_DISCOUNT_TICKET) FROM ORDERS;

-- 53. 月毎の注文件数を求める。抽出する列の名前は「年月」と「注文件数」とし、毎月列の内容は「202201」のような形式で、
--     日付の新しい順で抽出すること。なお、1件の注文には、必ず注文枝番「1」の注文明細が含まれることが保証されている。
SELECT CONCAT(SUBSTRING(ORDERS_DATE, 1, 4), SUBSTRING(ORDERS_DATE, 6, 2)) AS EVERY_MONTHS, COUNT(ORDERS_NUMBER) AS EVERY_MONTHS_ORDERS_SUM,
CASE COUNT(ORDERS_NUMBER) WHEN 1 THEN ORDERS_BRANCH_NUM
                          ELSE ''
END AS ORDERS_BRANCH_NUM
FROM ORDERS
GROUP BY EVERY_MONTHS
ORDER BY EVERY_MONTHS DESC;

-- 54. 注文テーブルから、「Z」から始まる商品コードのうち、これまでに売れた数量が100個以上の商品コードを抽出する。
SELECT PRODUCTS_CODE FROM ORDERS WHERE PRODUCTS_CODE LIKE 'Z%'
GROUP BY ORDERS_NUMBER
HAVING COUNT(PRODUCTS_CODE) >= 100;